### PR TITLE
chore: fix code coverage, drop ncp

### PR DESCRIPTION
**Pull request by kjin**
* `ncp` causes issues with running scripts locally. It hasn't been updated in 4 years, so I'm dropping it favor of ~~just `cp -r`~~ `cpy`.
* We were writing coverage info to `coverage` but `codecov` appears to expect these files to exist in `.coverage`.
* I disabled `--all` as it slows down CI a ton, enough to cause flakes.
* I added CI Codecov flags. Not 100% sure if it will work until we can view diffs, but this would allow different coverage reports for different Node versions.

### CODE REVIEW

**Comment by ofrobots** [comment]
`cp -r` wouldn't work on windows.

**Comment by kjin** [comment]
@ofrobots ah, thanks for the reminder.

**Comment by ofrobots** [comment]
For posterity, what are the problems that `ncp` is causing locally?

**Comment by kjin** [comment]
`ncp` has an issue where sometimes a callback isn't called. Since I promisify it that means a Promise won't resolve, and my build script never continues -- it just exits with error code 0. https://github.com/AvianFlu/ncp/issues/131 is an example, their issue list seems to suggest several such problems.

The repo and module seem unmaintained, so I don't have hope that this will be fixed.

**Pull request merged**
