### PR TITLE
fix: sample app TypeError

### LINKED ISSUE #1246: app sample broken: TypeError: The `GET` method cannot be used with a body
#### Environment details

  - OS: macOS
  - Node.js version: 10.20.1
  - npm version:   6.14.4
  - `@google-cloud/trace-agent` version: 4.2.5

#### Steps to reproduce

```
cd samples
npm install
npm start
curl localhost:8080
```

```
-> "TypeError: The `GET` method cannot be used with a body"
```

#### Notes

It looks like this example is using the `got` API wrongly: The `json` argument is supposed to be a serializable POJO, not a boolean: https://github.com/sindresorhus/got#json

### PR DESCRIPTION
**Pull request by ZiweiZhao**
App sample has error: TypeError: The `GET` method cannot be used with a body
This pull request is to update the body to an json response option

Fixes #1246 🦕

### CODE REVIEW

**Comment by bcoe** [comment]
failing Windows tests are being discussed here:

https://github.com/nodejs/node-gyp/issues/2114

**Comment by kintel** [comment]
@bcoe To move forward while the Node issues in question gets resolved (new Node version or new needle version), would it make sense to pin Node on Windows to 12.16.2 here? https://github.com/googleapis/cloud-trace-nodejs/blob/master/.github/workflows/ci.yaml#L61

**Comment by bcoe** [comment]
@kintel yes, I would just switch to Node 10 on this branch for the purposes of landing. I believe the upstream issue will be fixed soon in Node.

**Comment by JustinBeckwith** [comment]
Nice fix!  One question though - are we missing an integration test for the sample?  I'm a little surprised this didn't get captured in the end to end test.

**Comment by kintel** [comment]
@JustinBeckwith technically there is a test, but the test just checks that the process starts, not that it does the right thing. We should probably open a separate issue for improving the test.

**Comment by kintel** [comment]
Opened follow-up issue: #1259

**Pull request merged**
